import type { ReaderThemePackage } from './types';
import { APP_VERSION } from './version';

export const RECOMMENDED_THEME_PACKAGES: ReaderThemePackage[] = [
  {
    id: 'ink-focus',
    name: 'Ink Focus',
    version: '1.0.0',
    author: 'Local Markdown Reader',
    description: 'Neutral contrast for long technical documents.',
    minAppVersion: APP_VERSION,
    colorScheme: 'light',
    tokens: {
      '--markdown-font-size': '16px',
      '--markdown-line-height': '1.72',
      '--reader-page-bg': '#f4f6f8',
      '--reader-surface': '#ffffff',
      '--reader-border': '#d8dee7',
      '--reader-text': '#1f2933',
      '--reader-muted': '#64707d',
      '--reader-link': '#1f5f9f',
      '--reader-code-bg': '#edf1f5',
      '--reader-code-text': '#24303c',
      '--reader-table-head': '#f5f7fa',
      '--reader-table-stripe': '#f8fafc',
      '--reader-rule': '#d9e0e8',
      '--reader-quote-bg': '#f7f9fb',
      '--reader-quote-border': '#9aa8b7',
      '--reader-quote-text': '#53606c',
      '--reader-shadow': '0 14px 32px rgba(31, 41, 51, 0.08)',
    },
    css: '.document-reader h1, .document-reader h2, .document-reader h3 { letter-spacing: 0; } .document-reader table { font-variant-numeric: tabular-nums; }',
    installedAt: 0,
  },
  {
    id: 'night-study',
    name: 'Night Study',
    version: '1.0.0',
    author: 'Local Markdown Reader',
    description: 'Dark reading theme with restrained contrast.',
    minAppVersion: APP_VERSION,
    colorScheme: 'dark',
    tokens: {
      '--markdown-font-size': '16px',
      '--markdown-line-height': '1.75',
      '--reader-page-bg': '#0f141b',
      '--reader-surface': '#171f2a',
      '--reader-border': '#2d3a49',
      '--reader-text': '#e6edf5',
      '--reader-muted': '#9aa8b7',
      '--reader-link': '#8ab4ff',
      '--reader-code-bg': '#202b37',
      '--reader-code-text': '#e3eaf2',
      '--reader-table-head': '#1f2935',
      '--reader-table-stripe': '#1b2530',
      '--reader-rule': '#354252',
      '--reader-quote-bg': '#182330',
      '--reader-quote-border': '#52657d',
      '--reader-quote-text': '#c2ccd8',
      '--reader-shadow': '0 16px 36px rgba(0, 0, 0, 0.28)',
    },
    css: '.document-reader h1, .document-reader h2, .document-reader h3 { color: var(--reader-text); } .document-reader strong { color: #f2f6fb; }',
    installedAt: 0,
  },
  {
    id: 'report-grid',
    name: 'Report Grid',
    version: '1.0.0',
    author: 'Local Markdown Reader',
    description: 'Compact report style for tables and structured notes.',
    minAppVersion: APP_VERSION,
    colorScheme: 'system',
    tokens: {
      '--markdown-font-size': '15px',
      '--markdown-line-height': '1.62',
      '--reader-page-bg': '#f6f7f9',
      '--reader-surface': '#ffffff',
      '--reader-border': '#d7dde5',
      '--reader-text': '#202733',
      '--reader-muted': '#667280',
      '--reader-link': '#245da8',
      '--reader-code-bg': '#eef2f6',
      '--reader-code-text': '#243141',
      '--reader-table-head': '#edf2f7',
      '--reader-table-stripe': '#f8fafc',
      '--reader-rule': '#d7dde5',
      '--reader-quote-bg': '#f5f7fa',
      '--reader-quote-border': '#8795a7',
      '--reader-quote-text': '#56616f',
      '--reader-shadow': '0 10px 24px rgba(32, 39, 51, 0.06)',
    },
    css: '.document-reader table { font-variant-numeric: tabular-nums; } .document-reader th, .document-reader td { padding-top: 0.42em; padding-bottom: 0.42em; }',
    installedAt: 0,
  },
];
